// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxpnagxtimhnryvoivkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4cG5hZ3h0aW1obnJ5dm9pdmttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MTA2MTUsImV4cCI6MjA1Nzk4NjYxNX0.mXQl-v_0zKgDgXH1EL3Ltn7fw4Q3ptL25RHcL5-s0p0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);